### ISSUE TITLE
Webserver not working

### ISSUE THREAD

**Issue by mpuff** [weigu1/SmartyReader#3]
Hello, when i uncomment in the ESPBacker.h the line 4 #define WEBSERVER I get the error in v1.5:

`/Users/martinpuff/Documents/Arduino/SmartyReader_v1_5/ESPBacker.cpp: In member function 'void ESPBacker::init_http_server()':
ESPBacker.cpp:165:28: error: invalid use of non-static member function 'void ESPBacker::handle_not_found()'
  165 |     http_server.onNotFound(handle_not_found);
      |                            ^~~~~~~~~~~~~~~~
In file included from /Users/martinpuff/Documents/Arduino/SmartyReader_v1_5/ESPBacker.cpp:2:
/Users/martinpuff/Documents/Arduino/SmartyReader_v1_5/ESPBacker.h:94:12: note: declared here
   94 |       void handle_not_found();
      |            ^~~~~~~~~~~~~~~~
ESPBacker.cpp:166:25: error: invalid use of non-static member function 'void ESPBacker::handle_root()'
  166 |     http_server.on("/", handle_root);  // (don't forget the "/")
      |                         ^~~~~~~~~~~
In file included from /Users/martinpuff/Documents/Arduino/SmartyReader_v1_5/ESPBacker.cpp:2:
/Users/martinpuff/Documents/Arduino/SmartyReader_v1_5/ESPBacker.h:96:12: note: declared here
   96 |       void handle_root();
      |            ^~~~~~~~~~~
SmartyReader_v1_5:169:16: error: conflicting declaration 'char filename [13]'
  169 | char msg[128], filename[13];
      |                ^~~~~~~~
In file included from /Users/martinpuff/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WebServer/src/ESP8266WebServer.h:341,
                 from /Users/martinpuff/Documents/Arduino/SmartyReader_v1_5/ESPBacker.h:12,
                 from /Users/martinpuff/Documents/Arduino/SmartyReader_v1_5/SmartyReader_v1_5.ino:104:
/Users/martinpuff/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WebServer/src/Parsing-impl.h:33:19: note: previous declaration as 'const char filename [9]'
   33 | static const char filename[] PROGMEM = "filename";`

**Comment by weigu1** [comment]
The Webserver inside the ESPtool  library is not intended to use with the SmartyReader software (It is momentarily not working because I have problems to implement the callbacks of the webserver lib inside the class)
