### ISSUE TITLE
Libraries used in SmartyReader_v1_6_beta

### ISSUE THREAD

**Issue by BackenTrini** [weigu1/SmartyReader#4]
Hi,
is it possible to get a detailed list of libraries to install for compiling SmartyReader_v1_6_beta ?
As a beginner I have trouble finding the right ones.
Thanks.
BT.

**Comment by BackenTrini** [comment]
here are the errors I get:

SmartyReader_v1_6_beta:208:5: error: 'AES128' was not declared in this scope
  208 | GCM<AES128> *gcmaes128 = 0;
      |     ^~~~~~
SmartyReader_v1_6_beta:208:11: error: template argument 1 is invalid
  208 | GCM<AES128> *gcmaes128 = 0;
      |           ^
/Users/bt/Desktop/SmartyReader_v1_6_beta/SmartyReader_v1_6_beta.ino: In function 'void setup()':
SmartyReader_v1_6_beta:218:29: error: 'MQTT_MAXIMUM_PACKET_SIZE' was not declared in this scope; did you mean 'MQTT_MAX_PACKET_SIZE'?
  218 |   MQTT_Client.setBufferSize(MQTT_MAXIMUM_PACKET_SIZE);
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
      |                             MQTT_MAX_PACKET_SIZE
/Users/bt/Desktop/SmartyReader_v1_6_beta/SmartyReader_v1_6_beta.ino: In function 'void mqtt_publish_cooked()':
SmartyReader_v1_6_beta:393:31: error: 'MQTT_MAXIMUM_PACKET_SIZE' was not declared in this scope; did you mean 'MQTT_MAX_PACKET_SIZE'?
  393 |   DynamicJsonDocument doc_out(MQTT_MAXIMUM_PACKET_SIZE);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
      |                               MQTT_MAX_PACKET_SIZE
/Users/bt/Desktop/SmartyReader_v1_6_beta/SmartyReader_v1_6_beta.ino: In function 'void decrypt_text(Vector_GCM*)':
SmartyReader_v1_6_beta:679:23: error: 'AES128' was not declared in this scope
  679 |   gcmaes128 = new GCM<AES128>();
      |                       ^~~~~~
SmartyReader_v1_6_beta:679:29: error: template argument 1 is invalid
  679 |   gcmaes128 = new GCM<AES128>();
      |                             ^
SmartyReader_v1_6_beta:680:14: error: request for member 'setKey' in '* gcmaes128', which is of non-class type 'int'
  680 |   gcmaes128->setKey(vect->key, gcmaes128->keySize());
      |              ^~~~~~
SmartyReader_v1_6_beta:680:43: error: request for member 'keySize' in '* gcmaes128', which is of non-class type 'int'
  680 |   gcmaes128->setKey(vect->key, gcmaes128->keySize());
      |                                           ^~~~~~~
SmartyReader_v1_6_beta:681:14: error: request for member 'setIV' in '* gcmaes128', which is of non-class type 'int'
  681 |   gcmaes128->setIV(vect->iv, vect->ivsize);
      |              ^~~~~
SmartyReader_v1_6_beta:682:14: error: request for member 'decrypt' in '* gcmaes128', which is of non-class type 'int'
  682 |   gcmaes128->decrypt((uint8_t*)buffer, vect->ciphertext, vect->datasize);
      |              ^~~~~~~
Multiple libraries were found for "Ethernet.h"
 Used: /Users/bt/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/Ethernet
 Not used: /Applications/Arduino.app/Contents/Java/libraries/Ethernet
Multiple libraries were found for "AES.h"
 Used: /Users/bt/Documents/Arduino/libraries/AESLib
 Not used: /Users/bt/Documents/Arduino/libraries/Crypto
exit status 1
'AES128' was not declared in this scope


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by weigu1** [comment]
Thanks, I added the infos to the README file and corrected the missing MQTT_MAX_PACKET_SIZE in config.h
