### ISSUE TITLE
ESP32-POE-ISO sends mqtt messages in uneven time intervals

### ISSUE THREAD

**Issue by u20p17** [weigu1/SmartyReader#5]
Hi,
I am using a ESP32-POE-ISO which get powered by POE and is located near the smartmeter (Sagemcom T210-D-r). I already got the encryption key and modified your 1.6 beta code in order that the ethernet was working (and the general MQTT/network... settings in the config file.
After flashing an connecting I get some data via MQTT. As a test I set the publish time to 10s. As you can see it is working like expected and suddenly it stops for several minutes (more than 70min!) and after that it is working again for some mqtt messages and then it stops again for a long time.

![mqtt](https://user-images.githubusercontent.com/63282286/177706564-1817d3a8-2cc3-441a-af5d-81fcbf6cc014.JPG)

What could be the problem?

Furthermore, lot of the channels are just 0. Is this a problem of my smartmeter ( maybe the energy company has to activate them?) or might it be related to the code?

![mqqt_messages](https://user-images.githubusercontent.com/63282286/177705627-1761abd8-29d3-44ec-96d7-032ffd0510ee.JPG)

Here my updated code:
[SmartyReader_v1_6_beta.zip](https://github.com/weigu1/SmartyReader/files/9060960/SmartyReader_v1_6_beta.zip)

Thanks in advance!

**Comment by weigu1** [comment]
Hi there,

First the simple question :) The zeros are related  to your energy company. In Luxembourg they sent in the beginning 700 bytes with the currents per phase, then after an update only 500 bytes without the currents. After some clients complained they now sent also the power per phase (1100 byte). So ask your company for more data.

I had the same problems in the beginning of the year with ESP32. They worked sometimes one week without complaint and then stopped for some hours without logging errors. I had no time to dig deeper and replaced them with ESP8266. We also had other problems with ESP32 that could be solved by downgrading on a core version before 3.0. So perhaps you could try this (in Boards manager you can choose the version). 
Another problem could be a not enough or stable power supply (add a big capacitor).

Sorry, but for the moment I can't look into this more deeply.

Greetings 
Guy

**Comment by u20p17** [comment]
Hi,
Thanks for the answer. I will contact the energy company and ask if they can also activate the full data output of the smartmeter.

Do you have a complete set that you could sell me? Would save me some work for soldering the platine ;)

Thanks!

**Comment by weigu1** [comment]
Hi, 
For a kit, please send me your address to weigu@weigu.lu.
Greetings
